---
- name: create user groups
  group:
    name: "{{ item.name }}"
    system: "{{ item.system }}"
  with_items: "{{ users }}"

- name: create users
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    shell: "{{ item.shell }}"
    home: "/home/{{ item.name }}"
    system: "{{ item.system }}"
  with_items: "{{ users }}"

- name: set home directory permissions
  file:
    path: "/home/{{ item.name }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  with_items: "{{ users }}"

- name: configure authorized_keys
  authorized_key:
    key: "{{ item.key }}"
    user: "{{ item.name }}"
  with_items: "{{ users }}"
